on: [push]

jobs:
  check_for_conflicts_job:
    runs-on: ubuntu-latest
    name: Check for merge conflicts
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v1
      # Run the actual conflict finder
      - name: Check for Conflicts Action
        uses: actions/check-for-conflicts-action@v1
        with:
          who-to-greet: 'Noviicee'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      
